Find size of size_t so we can use it to create FFSEncodeVector structure.
git-svn-id: http://svn.research.cc.gatech.edu/kaos/ffs/trunk@3399 8ba6a8b9-845b-0410-94f0-974be2f5df47

diff --git a/ffs/configure b/ffs/configure
--- a/ffs/configure
+++ b/ffs/configure
@@ -889,6 +889,7 @@ DCG_LALIB
 FFS_GEN_O
 DCG_WILD
 DCG_DEPEND
+UIO_SIZE_T_TYPE
 SPECIAL_TEST_TARGET
 SPECIAL_TEST_DIR
 check_files
@@ -1507,7 +1508,6 @@ Optional Packages:
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-installed        Don't use local copies of CERCS packages
   --with-local            Use only local copies of CERCS packages
-  --with-fm=DIR	Where to find fm package
   --with-cercs_env=DIR	Where to find cercs_env package
   --with-dill=DIR	Where to find dill package
   --with-gcrypt=DIR	Where to find gcrypt package
@@ -10799,289 +10799,6 @@ if test -z "$with_local_specified"; then
 
 
 
-# Check whether --with-fm was given.
-if test "${with_fm+set}" = set; then
-  withval=$with_fm;
-fi
-
-
-if test -n "$with_fm"; then
-unset cercs_cv_fm_include_arg
-unset cercs_cv_fm_link_arg
-if test `echo $with_fm | sed 's/\(.\).*/\1/g'` != "/"; then
-with_fm=`pwd`/$with_fm
-fi
-fi
-{ echo "$as_me:$LINENO: checking needed include args for fm package" >&5
-echo $ECHO_N "checking needed include args for fm package... $ECHO_C" >&6; }
-if test "${cercs_cv_fm_include_arg+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-
-
-
-cercs_tmp=""
-search_list="./fm.h"
-CHAOS_HOMEDIR=""
-if test -n "$CSH"; then
-CHAOS_HOMEDIR=`echo "echo ~chaos" | csh -sf  2>/dev/null | sed 's%/$%%'` || CHAOS_HOMEDIR=""
-fi
-if test -n "$with_fm"; then
-if test `echo $with_fm | cut -c1` = "~"; then
-EXPANDED=`echo "echo $with_fm" | csh -sf 2>/dev/null` || EXPANDED=""
-else
-EXPANDED=$with_fm
-fi
-
-search_list="$search_list $EXPANDED/fm.h $EXPANDED/include/fm.h $EXPANDED/share/fm.h $EXPANDED/$cercs_cv_archive/fm.h $EXPANDED/$cercs_cv_archive/include/fm.h $EXPANDED/fm/fm.h $EXPANDED/fm/$cercs_cv_archive/fm.h $EXPANDED/fm/include/fm.h $EXPANDED/fm/include/$cercs_cv_archive/fm.h"
-fi
-if test -z "$with_installed_specified"; then
-search_list="$search_list `pwd`/../fm/fm.h `pwd`/../include/fm.h `pwd`/../share/fm.h $HOME/fm/fm.h $HOME/$cercs_cv_archive/include/fm.h $HOME/include/fm.h"
-fi
-if test "$libdir" != '${exec_prefix}/lib'; then
-tmpdir=`echo ${libdir} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/fm.h"
-fi
-if test "$exec_prefix" != "NONE"; then
-tmpdir=`echo ${exec_prefix} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/lib/fm.h"
-fi
-if test "$includedir" != '${prefix}/include'; then
-tmpdir=`echo ${includedir} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/fm.h"
-fi
-if test "$prefix" != "NONE"; then
-tmpdir=`echo ${prefix} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/include/fm.h"
-fi
-if test -n "$CHAOS_HOMEDIR" -a -n "$cercs_cv_archive"; then
-search_list="$search_list $CHAOS_HOMEDIR/include/fm.h $CHAOS_HOMEDIR/$cercs_cv_archive/include/fm.h $CHAOS_HOMEDIR/fm/$cercs_cv_archive/include/fm.h $CHAOS_HOMEDIR/fm/include/fm.h"
-fi
-search_list="$search_list /usr/include/fm.h /usr/local/include/fm.h /opt/fm/include/fm.h /opt/misc/include/fm.h /opt/misc/include/$cercs_cv_archive/fm.h"
-tmp_search_results=""
-echo "configure:10863: searching for $search_list " >&5
-for tmp_search_value in $search_list; do
-   if test -r $tmp_search_value; then
-	tmp_search_results=$tmp_search_value
-	echo "configure:10867: first found $tmp_search_results " >&5
-	break
-   fi
-done
-
-if test -n "$tmp_search_results"; then
-cercs_tmp=$tmp_search_results
-fi
-
-if test -n "$cercs_tmp" -a "$cercs_tmp" != "/usr/include/fm.h"; then
-cercs_cv_fm_include_arg=-I`$PATHPROG $cercs_tmp | sed 's#\\\\#/#g' | sed "s#.fm.h##g"`
-fi
-
-fi
-
-{ echo "$as_me:$LINENO: result: $cercs_cv_fm_include_arg" >&5
-echo "${ECHO_T}$cercs_cv_fm_include_arg" >&6; }
-if test -n "$cercs_cv_fm_include_arg"; then
-arg="$cercs_cv_fm_include_arg"
-no_dash_arg=`echo $arg | sed 's/^-//g'`
-if test `echo $CPPFLAGS | grep -c "$no_dash_arg"` -eq 0; then
-if test `echo $arg | grep -c "fm"` -eq 0; then
-CPPFLAGS="$CPPFLAGS $arg";
-else
-CPPFLAGS="$arg $CPPFLAGS"
-fi
-fi
-fi
-
-{ echo "$as_me:$LINENO: checking needed link args for fm package" >&5
-echo $ECHO_N "checking needed link args for fm package... $ECHO_C" >&6; }
-if test "${cercs_cv_fm_link_dir+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-
-
-
-cercs_tmp=""
-search_list="./libfm.la"
-CHAOS_HOMEDIR=""
-if test -n "$CSH"; then
-CHAOS_HOMEDIR=`echo "echo ~chaos" | csh -sf  2>/dev/null | sed 's%/$%%'` || CHAOS_HOMEDIR=""
-fi
-if test -n "$with_fm"; then
-if test `echo $with_fm | cut -c1` = "~"; then
-EXPANDED=`echo "echo $with_fm" | csh -sf 2>/dev/null` || EXPANDED=""
-else
-EXPANDED=$with_fm
-fi
-
-search_list="$search_list $EXPANDED/libfm.la $EXPANDED/lib/libfm.la $EXPANDED/share/libfm.la $EXPANDED/$cercs_cv_archive/libfm.la $EXPANDED/$cercs_cv_archive/lib/libfm.la $EXPANDED/fm/libfm.la $EXPANDED/fm/$cercs_cv_archive/libfm.la $EXPANDED/fm/lib/libfm.la $EXPANDED/fm/lib/$cercs_cv_archive/libfm.la"
-fi
-if test -z "$with_installed_specified"; then
-search_list="$search_list `pwd`/../fm/libfm.la `pwd`/../lib/libfm.la `pwd`/../share/libfm.la $HOME/fm/libfm.la $HOME/$cercs_cv_archive/lib/libfm.la $HOME/lib/libfm.la"
-fi
-if test "$libdir" != '${exec_prefix}/lib'; then
-tmpdir=`echo ${libdir} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/libfm.la"
-fi
-if test "$exec_prefix" != "NONE"; then
-tmpdir=`echo ${exec_prefix} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/lib/libfm.la"
-fi
-if test "$includedir" != '${prefix}/include'; then
-tmpdir=`echo ${includedir} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/libfm.la"
-fi
-if test "$prefix" != "NONE"; then
-tmpdir=`echo ${prefix} |  sed 's%/$%%'`
-search_list="$search_list $tmpdir/lib/libfm.la"
-fi
-if test -n "$CHAOS_HOMEDIR" -a -n "$cercs_cv_archive"; then
-search_list="$search_list $CHAOS_HOMEDIR/lib/libfm.la $CHAOS_HOMEDIR/$cercs_cv_archive/lib/libfm.la $CHAOS_HOMEDIR/fm/$cercs_cv_archive/lib/libfm.la $CHAOS_HOMEDIR/fm/lib/libfm.la"
-fi
-search_list="$search_list /usr/lib/libfm.la /usr/local/lib/libfm.la /opt/fm/lib/libfm.la /opt/misc/lib/libfm.la /opt/misc/lib/$cercs_cv_archive/libfm.la"
-tmp_search_results=""
-echo "configure:10944: searching for $search_list " >&5
-for tmp_search_value in $search_list; do
-   if test -r $tmp_search_value; then
-	tmp_search_results=$tmp_search_value
-	echo "configure:10948: first found $tmp_search_results " >&5
-	break
-   fi
-done
-
-if test -n "$tmp_search_results"; then
-cercs_tmp=$tmp_search_results
-fi
-
-if test -n "$cercs_tmp" -a "$cercs_tmp" != "libfm.la"; then
-cercs_cv_fm_link_dir=`$PATHPROG $cercs_tmp | sed 's#\\\\#/#g' | sed "s/.libfm.la//g"`
-else
-cercs_cv_fm_link_dir=""
-fi
-
-fi
-
-{ echo "$as_me:$LINENO: result: $cercs_cv_fm_link_dir" >&5
-echo "${ECHO_T}$cercs_cv_fm_link_dir" >&6; }
-ld_arg="-L"
-new_flags=$LDFLAGS
-cercs_cv_fm_link_arg=`echo $cercs_cv_fm_link_dir | sed "/./ s/^/$ld_arg/1"`
-if test -n "$cercs_cv_fm_link_arg"; then
-arg=$cercs_cv_fm_link_arg
-no_dash_arg=`echo $arg | sed 's/^-//g'`
-if test `echo $new_flags | grep -c "$no_dash_arg"` -eq 0; then
-root=`echo libfm.la | sed 's/\..*//'`
-if test ! -r $cercs_cv_fm_link_dir/$root.la; then
-if eval "test \"\${LIBTOOL+set}\" = set"; then
-arg="$cercs_cv_fm_link_arg "`echo $cercs_cv_fm_link_dir | sed "/./ s/^/-R/1"`
-fi
-fi
-if test `echo $arg | grep -c "fm"` -eq 0; then
-new_flags="$new_flags $arg"
-else
-new_flags="$arg $new_flags"
-fi
-fi
-LDFLAGS=$new_flags
-fi
-
-
-else
-
-
-
-
-# Check whether --with-fm was given.
-if test "${with_fm+set}" = set; then
-  withval=$with_fm;
-fi
-
-
-if test -n "$with_fm"; then
-unset cercs_cv_fm_include_arg
-unset cercs_cv_fm_link_arg
-if test `echo $with_fm | sed 's/\(.\).*/\1/g'` != "/"; then
-with_fm=`pwd`/$with_fm
-fi
-fi
-{ echo "$as_me:$LINENO: checking needed include args for fm package" >&5
-echo $ECHO_N "checking needed include args for fm package... $ECHO_C" >&6; }
-if test "${cercs_cv_fm_include_arg+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-cercs_tmp=`pwd`/../fm
-if test -n "$cercs_tmp" -a "$cercs_tmp" != "/usr/include/fm.h"; then
-cercs_cv_fm_include_arg=-I`$PATHPROG $cercs_tmp | sed 's#\\\\#/#g' | sed "s#.fm.h##g"`
-fi
-
-fi
-
-{ echo "$as_me:$LINENO: result: $cercs_cv_fm_include_arg" >&5
-echo "${ECHO_T}$cercs_cv_fm_include_arg" >&6; }
-if test -n "$cercs_cv_fm_include_arg"; then
-arg="$cercs_cv_fm_include_arg"
-no_dash_arg=`echo $arg | sed 's/^-//g'`
-if test `echo $CPPFLAGS | grep -c "$no_dash_arg"` -eq 0; then
-if test `echo $arg | grep -c "fm"` -eq 0; then
-CPPFLAGS="$CPPFLAGS $arg";
-else
-CPPFLAGS="$arg $CPPFLAGS"
-fi
-fi
-fi
-
-{ echo "$as_me:$LINENO: checking needed link args for fm package" >&5
-echo $ECHO_N "checking needed link args for fm package... $ECHO_C" >&6; }
-if test "${cercs_cv_fm_link_dir+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-cercs_tmp=`pwd`/../fm
-if test -n "$cercs_tmp" -a "$cercs_tmp" != "libfm.la"; then
-cercs_cv_fm_link_dir=`$PATHPROG $cercs_tmp | sed 's#\\\\#/#g' | sed "s/.libfm.la//g"`
-else
-cercs_cv_fm_link_dir=""
-fi
-
-fi
-
-{ echo "$as_me:$LINENO: result: $cercs_cv_fm_link_dir" >&5
-echo "${ECHO_T}$cercs_cv_fm_link_dir" >&6; }
-ld_arg="-L"
-new_flags=$LDFLAGS
-cercs_cv_fm_link_arg=`echo $cercs_cv_fm_link_dir | sed "/./ s/^/$ld_arg/1"`
-if test -n "$cercs_cv_fm_link_arg"; then
-arg=$cercs_cv_fm_link_arg
-no_dash_arg=`echo $arg | sed 's/^-//g'`
-if test `echo $new_flags | grep -c "$no_dash_arg"` -eq 0; then
-root=`echo libfm.la | sed 's/\..*//'`
-if test ! -r $cercs_cv_fm_link_dir/$root.la; then
-if eval "test \"\${LIBTOOL+set}\" = set"; then
-arg="$cercs_cv_fm_link_arg "`echo $cercs_cv_fm_link_dir | sed "/./ s/^/-R/1"`
-fi
-fi
-if test `echo $arg | grep -c "fm"` -eq 0; then
-new_flags="$new_flags $arg"
-else
-new_flags="$arg $new_flags"
-fi
-fi
-LDFLAGS=$new_flags
-fi
-
-
-fi
-
-
-
-
-if test -z "$with_local_specified"; then
-
-
-
-
 # Check whether --with-cercs_env was given.
 if test "${with_cercs_env+set}" = set; then
   withval=$with_cercs_env;
@@ -11143,11 +10860,11 @@ search_list="$search_list $CHAOS_HOMEDIR/include/cercs_env.h $CHAOS_HOMEDIR/$cer
 fi
 search_list="$search_list /usr/include/cercs_env.h /usr/local/include/cercs_env.h /opt/cercs_env/include/cercs_env.h /opt/misc/include/cercs_env.h /opt/misc/include/$cercs_cv_archive/cercs_env.h"
 tmp_search_results=""
-echo "configure:11146: searching for $search_list " >&5
+echo "configure:10863: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:11150: first found $tmp_search_results " >&5
+	echo "configure:10867: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -11224,11 +10941,11 @@ search_list="$search_list $CHAOS_HOMEDIR/lib/libcercs_env.la $CHAOS_HOMEDIR/$cer
 fi
 search_list="$search_list /usr/lib/libcercs_env.la /usr/local/lib/libcercs_env.la /opt/cercs_env/lib/libcercs_env.la /opt/misc/lib/libcercs_env.la /opt/misc/lib/$cercs_cv_archive/libcercs_env.la"
 tmp_search_results=""
-echo "configure:11227: searching for $search_list " >&5
+echo "configure:10944: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:11231: first found $tmp_search_results " >&5
+	echo "configure:10948: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -11426,11 +11143,11 @@ search_list="$search_list $CHAOS_HOMEDIR/include/dill.h $CHAOS_HOMEDIR/$cercs_cv
 fi
 search_list="$search_list /usr/include/dill.h /usr/local/include/dill.h /opt/dill/include/dill.h /opt/misc/include/dill.h /opt/misc/include/$cercs_cv_archive/dill.h"
 tmp_search_results=""
-echo "configure:11429: searching for $search_list " >&5
+echo "configure:11146: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:11433: first found $tmp_search_results " >&5
+	echo "configure:11150: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -11507,11 +11224,11 @@ search_list="$search_list $CHAOS_HOMEDIR/lib/libdill.la $CHAOS_HOMEDIR/$cercs_cv
 fi
 search_list="$search_list /usr/lib/libdill.la /usr/local/lib/libdill.la /opt/dill/lib/libdill.la /opt/misc/lib/libdill.la /opt/misc/lib/$cercs_cv_archive/libdill.la"
 tmp_search_results=""
-echo "configure:11510: searching for $search_list " >&5
+echo "configure:11227: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:11514: first found $tmp_search_results " >&5
+	echo "configure:11231: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -12814,11 +12531,11 @@ search_list="$search_list $CHAOS_HOMEDIR/include/gcrypt.h $CHAOS_HOMEDIR/$cercs_
 fi
 search_list="$search_list /usr/include/gcrypt.h /usr/local/include/gcrypt.h /opt/gcrypt/include/gcrypt.h /opt/misc/include/gcrypt.h /opt/misc/include/$cercs_cv_archive/gcrypt.h"
 tmp_search_results=""
-echo "configure:12817: searching for $search_list " >&5
+echo "configure:12534: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:12821: first found $tmp_search_results " >&5
+	echo "configure:12538: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -12895,11 +12612,11 @@ search_list="$search_list $CHAOS_HOMEDIR/lib/libgcrypt.a $CHAOS_HOMEDIR/$cercs_c
 fi
 search_list="$search_list /usr/lib/libgcrypt.a /usr/local/lib/libgcrypt.a /opt/gcrypt/lib/libgcrypt.a /opt/misc/lib/libgcrypt.a /opt/misc/lib/$cercs_cv_archive/libgcrypt.a"
 tmp_search_results=""
-echo "configure:12898: searching for $search_list " >&5
+echo "configure:12615: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:12902: first found $tmp_search_results " >&5
+	echo "configure:12619: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -13307,6 +13024,135 @@ _ACEOF
 
 fi
 
+{ echo "$as_me:$LINENO: checking for size_t" >&5
+echo $ECHO_N "checking for size_t... $ECHO_C" >&6; }
+if test "${ac_cv_type_size_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+typedef size_t ac__type_new_;
+int
+main ()
+{
+if ((ac__type_new_ *) 0)
+  return 0;
+if (sizeof (ac__type_new_))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_type_size_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_type_size_t=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_type_size_t" >&5
+echo "${ECHO_T}$ac_cv_type_size_t" >&6; }
+if test $ac_cv_type_size_t = yes; then
+  :
+else
+
+cat >>confdefs.h <<_ACEOF
+#define size_t unsigned int
+_ACEOF
+
+fi
+
+{ echo "$as_me:$LINENO: checking size of size_t" >&5
+echo $ECHO_N "checking size of size_t... $ECHO_C" >&6; }
+if test "${ac_cv_sizeof_size_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  for ac_size in 4 8 1 2 16  ; do # List sizes in rough order of prevalence.
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "confdefs.h"
+#include <sys/types.h>
+
+
+int
+main ()
+{
+switch (0) case 0: case (sizeof (size_t) == $ac_size):;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_sizeof_size_t=$ac_size
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  if test x$ac_cv_sizeof_size_t != x ; then break; fi
+done
+
+fi
+
+if test x$ac_cv_sizeof_size_t = x ; then
+  ac_cv_sizeof_size_t=0;
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_sizeof_size_t" >&5
+echo "${ECHO_T}$ac_cv_sizeof_size_t" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define SIZEOF_SIZE_T $ac_cv_sizeof_size_t
+_ACEOF
+
+
 { echo "$as_me:$LINENO: checking size of int" >&5
 echo $ECHO_N "checking size of int... $ECHO_C" >&6; }
 if test "${ac_cv_sizeof_int+set}" = set; then
@@ -13703,6 +13549,12 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+
+if test $ac_cv_sizeof_size_t -eq $ac_cv_sizeof_int ; then
+   UIO_SIZE_T_TYPE="unsigned int"
+elif test $ac_cv_sizeof_size_t -eq $ac_cv_sizeof_long; then
+   UIO_SIZE_T_TYPE="unsigned long";
+fi
 
 LIBS="$LIBS -lcercs_env"
 
@@ -14856,6 +14708,7 @@ DCG_LALIB!$DCG_LALIB$ac_delim
 FFS_GEN_O!$FFS_GEN_O$ac_delim
 DCG_WILD!$DCG_WILD$ac_delim
 DCG_DEPEND!$DCG_DEPEND$ac_delim
+UIO_SIZE_T_TYPE!$UIO_SIZE_T_TYPE$ac_delim
 SPECIAL_TEST_TARGET!$SPECIAL_TEST_TARGET$ac_delim
 SPECIAL_TEST_DIR!$SPECIAL_TEST_DIR$ac_delim
 check_files!$check_files$ac_delim
@@ -14864,7 +14717,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
